version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501" # Streamlit 기본 포트
    volumes:
      - ./volumes/original:/volumes/original
      - ./volumes/preprocessed:/volumes/preprocessed
      - ./volumes/ocr_results:/volumes/ocr_results
      - ./ocr_frontend:/app/frontend # 로컬 ./frontend 디렉토리를 컨테이너 /app/frontend로 마운트

  preprocessor:
    build:
      context: .
      dockerfile: Dockerfile.preprocessor
    container_name: preprocessor
    ports:
      - "5001:5001"
    volumes:
      - ./volumes/original:/volumes/original
      - ./volumes/preprocessed:/volumes/preprocessed
      - ./ocr_preprocessor:/app/preprocessor # 로컬 ./preprocessor 디렉토리를 컨테이너 /app/preprocessor로 마운트

    tty: true
    stdin_open: true
    mem_limit: 7g

  ocr_server:
    build:
      context: .
      dockerfile: Dockerfile.ocr
    container_name: ocr_server
    ports:
      - "8082:8082"
    volumes:
      - ./volumes/preprocessed:/volumes/preprocessed
      - ./volumes/ocr_results:/volumes/ocr_results
      - ./ocr_server:/app/ocr_server # 로컬 ./ocr_server 디렉토리를 컨테이너 /app/ocr_server로 마운트
